const DB_KEY='auron-vault-v1';
let vault=[];let key=null;let locked=true;
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function b64(bytes){let s='';bytes.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}
function unb64(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
async function derive(password,salt){return crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']).then(base=>crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']))}
async function encrypt(data,k){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(JSON.stringify(data)));return {iv:b64(iv),data:b64(new Uint8Array(ct))}}
async function decrypt(box,k){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},k,unb64(box.data));return JSON.parse(new TextDecoder().decode(pt))}
async function save(){const raw=localStorage.getItem(DB_KEY);if(!raw)return;const meta=JSON.parse(raw);const box=await encrypt(vault,key);localStorage.setItem(DB_KEY,JSON.stringify({version:1,salt:meta.salt,box}))}
function randomPassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=';const a=new Uint32Array(24);crypto.getRandomValues(a);return Array.from(a,x=>chars[x%chars.length]).join('')}
function render(){const q=$('search').value.trim().toLowerCase();const list=vault.filter(e=>(e.name+' '+e.user+' '+e.url).toLowerCase().includes(q));$('count').textContent=` · ${vault.length}`;$('entries').innerHTML=list.length?list.map(e=>`<article class="entry"><div class="entryIcon">${escapeHtml((e.name||'?')[0].toUpperCase())}</div><div class="entryMain"><div class="entryName">${escapeHtml(e.name)}</div><div class="entryUser">${escapeHtml(e.user||'')}</div></div><div class="entryActions"><button data-view="${e.id}">Anzeigen</button></div></article>`).join(''):'<div class="empty">Noch keine Einträge.<br>Tippe auf ＋, um einen anzulegen.</div>'}
function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openNew(){ $('entryForm').reset();$('entryId').value='';$('dialogTitle').textContent='Neuer Eintrag';$('entryDialog').showModal() }
function openEdit(id){const e=vault.find(x=>x.id===id);if(!e)return;$('entryId').value=e.id;$('entryName').value=e.name;$('entryUrl').value=e.url||'';$('entryUser').value=e.user||'';$('entryPass').value=e.pass;$('entryNote').value=e.note||'';$('dialogTitle').textContent='Eintrag bearbeiten';$('entryDialog').showModal()}
$('setupForm').addEventListener('submit',async e=>{e.preventDefault();const p=$('setupPassword').value;if(p.length<12||p!==$('setupPassword2').value)return alert('Passwörter müssen übereinstimmen und mindestens 12 Zeichen lang sein.');const salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);vault=[];const box=await encrypt(vault,key);localStorage.setItem(DB_KEY,JSON.stringify({version:1,salt:b64(salt),box}));$('setupForm').reset();locked=false;show('vault');render()});
$('unlockForm').addEventListener('submit',async e=>{e.preventDefault();$('unlockError').textContent='';try{const meta=JSON.parse(localStorage.getItem(DB_KEY));key=await derive($('unlockPassword').value,unb64(meta.salt));vault=await decrypt(meta.box,key);locked=false;$('unlockPassword').value='';show('vault');render()}catch{$('unlockError').textContent='Falsches Master-Passwort oder beschädigter Tresor.';key=null}});
$('addBtn').addEventListener('click',openNew);$('search').addEventListener('input',render);$('lockBtn').addEventListener('click',()=>{vault=[];key=null;locked=true;show('unlock')});$('generateBtn').addEventListener('click',()=>{$('entryPass').value=randomPassword();$('entryPass').type='text';setTimeout(()=>$('entryPass').type='password',1200)});
$('entryForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('entryId').value||crypto.randomUUID();const item={id,name:$('entryName').value.trim(),url:$('entryUrl').value.trim(),user:$('entryUser').value,pass:$('entryPass').value,note:$('entryNote').value};const i=vault.findIndex(x=>x.id===id);if(i>=0)vault[i]=item;else vault.push(item);await save();$('entryDialog').close();render()});
$('entries').addEventListener('click',e=>{const btn=e.target.closest('[data-view]');if(!btn)return;const item=vault.find(x=>x.id===btn.dataset.view);if(item)openEdit(item.id)});
window.addEventListener('beforeunload',()=>{key=null;vault=[]});
(async()=>{if(!window.crypto?.subtle){document.body.innerHTML='<p style="padding:30px">Dieser Browser unterstützt die benötigte Web-Kryptografie nicht.</p>';return}const raw=localStorage.getItem(DB_KEY);show(raw?'unlock':'setup')})();
